<x-layouts.public
    :title="__('public.meta.docs_title')"
    :description="__('public.meta.docs_description')"
>
    <x-pages.docs
        :docs-link-example="$docsLinkExample"
        :docs-api-calendar-example="$docsApiCalendarExample"
        :docs-api-json-example="$docsApiJsonExample"
        :docs-mcp-details="$docsMcpDetails"
        :docs-examples="$docsExamples"
    />
</x-layouts.public>
